# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies (ignore prepare scripts if needed)
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the application
RUN npm run build

EXPOSE 3000

# Start the MCP server
CMD ["node", "dist/index.js"]
